# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainwindow(object):
    def setupUi(self, mainwindow):
        mainwindow.setObjectName("mainwindow")
        mainwindow.resize(781, 560)
        self.receiveWin = QtWidgets.QGroupBox(mainwindow)
        self.receiveWin.setGeometry(QtCore.QRect(30, 20, 491, 381))
        self.receiveWin.setObjectName("receiveWin")
        self.receiveTxt = QtWidgets.QTextBrowser(self.receiveWin)
        self.receiveTxt.setGeometry(QtCore.QRect(0, 20, 491, 361))
        self.receiveTxt.setObjectName("receiveTxt")
        self.sendWin = QtWidgets.QGroupBox(mainwindow)
        self.sendWin.setGeometry(QtCore.QRect(30, 420, 491, 121))
        self.sendWin.setObjectName("sendWin")
        self.sendTxt = QtWidgets.QTextEdit(self.sendWin)
        self.sendTxt.setGeometry(QtCore.QRect(0, 16, 491, 101))
        self.sendTxt.setObjectName("sendTxt")
        self.uartWin = QtWidgets.QGroupBox(mainwindow)
        self.uartWin.setEnabled(True)
        self.uartWin.setGeometry(QtCore.QRect(530, 30, 221, 371))
        self.uartWin.setTitle("")
        self.uartWin.setFlat(False)
        self.uartWin.setCheckable(False)
        self.uartWin.setObjectName("uartWin")
        self.qingkong = QtWidgets.QPushButton(self.uartWin)
        self.qingkong.setGeometry(QtCore.QRect(120, 310, 101, 31))
        self.qingkong.setObjectName("qingkong")
        self.hexDisplay = QtWidgets.QCheckBox(self.uartWin)
        self.hexDisplay.setGeometry(QtCore.QRect(0, 310, 101, 31))
        self.hexDisplay.setObjectName("hexDisplay")
        self.comTest = QtWidgets.QPushButton(self.uartWin)
        self.comTest.setGeometry(QtCore.QRect(120, 10, 101, 31))
        self.comTest.setObjectName("comTest")
        self.comboBox_com = QtWidgets.QComboBox(self.uartWin)
        self.comboBox_com.setGeometry(QtCore.QRect(0, 10, 111, 31))
        self.comboBox_com.setObjectName("comboBox_com")
        self.comboBox_baud = QtWidgets.QComboBox(self.uartWin)
        self.comboBox_baud.setGeometry(QtCore.QRect(120, 60, 101, 31))
        self.comboBox_baud.setEditable(False)
        self.comboBox_baud.setDuplicatesEnabled(False)
        self.comboBox_baud.setObjectName("comboBox_baud")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_stop = QtWidgets.QComboBox(self.uartWin)
        self.comboBox_stop.setGeometry(QtCore.QRect(120, 100, 101, 31))
        self.comboBox_stop.setObjectName("comboBox_stop")
        self.comboBox_stop.addItem("")
        self.comboBox_data = QtWidgets.QComboBox(self.uartWin)
        self.comboBox_data.setGeometry(QtCore.QRect(120, 140, 101, 31))
        self.comboBox_data.setObjectName("comboBox_data")
        self.comboBox_data.addItem("")
        self.comboBox_data.addItem("")
        self.comboBox_data.addItem("")
        self.comboBox_data.addItem("")
        self.comboBox_odd = QtWidgets.QComboBox(self.uartWin)
        self.comboBox_odd.setGeometry(QtCore.QRect(120, 180, 101, 31))
        self.comboBox_odd.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.comboBox_odd.setObjectName("comboBox_odd")
        self.comboBox_odd.addItem("")
        self.comboBox_odd.addItem("")
        self.comboBox_odd.addItem("")
        self.openbotton = QtWidgets.QPushButton(self.uartWin)
        self.openbotton.setGeometry(QtCore.QRect(0, 230, 101, 41))
        self.openbotton.setObjectName("openbotton")
        self.label_baud = QtWidgets.QLabel(self.uartWin)
        self.label_baud.setGeometry(QtCore.QRect(20, 60, 72, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        self.label_baud.setFont(font)
        self.label_baud.setTextFormat(QtCore.Qt.AutoText)
        self.label_baud.setObjectName("label_baud")
        self.label_stop = QtWidgets.QLabel(self.uartWin)
        self.label_stop.setGeometry(QtCore.QRect(20, 100, 72, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        self.label_stop.setFont(font)
        self.label_stop.setTextFormat(QtCore.Qt.AutoText)
        self.label_stop.setObjectName("label_stop")
        self.label_data = QtWidgets.QLabel(self.uartWin)
        self.label_data.setGeometry(QtCore.QRect(20, 140, 72, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        self.label_data.setFont(font)
        self.label_data.setTextFormat(QtCore.Qt.AutoText)
        self.label_data.setObjectName("label_data")
        self.label_odd = QtWidgets.QLabel(self.uartWin)
        self.label_odd.setGeometry(QtCore.QRect(20, 180, 72, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        self.label_odd.setFont(font)
        self.label_odd.setTextFormat(QtCore.Qt.AutoText)
        self.label_odd.setObjectName("label_odd")
        self.closebotton = QtWidgets.QPushButton(self.uartWin)
        self.closebotton.setGeometry(QtCore.QRect(120, 230, 101, 41))
        self.closebotton.setObjectName("closebotton")
        self.send_caozuo = QtWidgets.QGroupBox(mainwindow)
        self.send_caozuo.setGeometry(QtCore.QRect(530, 430, 221, 101))
        self.send_caozuo.setTitle("")
        self.send_caozuo.setObjectName("send_caozuo")
        self.sendbotton = QtWidgets.QPushButton(self.send_caozuo)
        self.sendbotton.setGeometry(QtCore.QRect(120, 30, 93, 41))
        self.sendbotton.setObjectName("sendbotton")
        self.hexSend = QtWidgets.QCheckBox(self.send_caozuo)
        self.hexSend.setGeometry(QtCore.QRect(0, 20, 101, 31))
        self.hexSend.setObjectName("hexSend")
        self.xinhang = QtWidgets.QCheckBox(self.send_caozuo)
        self.xinhang.setGeometry(QtCore.QRect(0, 50, 91, 41))
        self.xinhang.setObjectName("xinhang")

        self.retranslateUi(mainwindow)
        QtCore.QMetaObject.connectSlotsByName(mainwindow)

    def retranslateUi(self, mainwindow):
        _translate = QtCore.QCoreApplication.translate
        mainwindow.setWindowTitle(_translate("mainwindow", "串口助手"))
        self.receiveWin.setTitle(_translate("mainwindow", "接收窗口"))
        self.sendWin.setTitle(_translate("mainwindow", "发送窗口"))
        self.qingkong.setText(_translate("mainwindow", "清空接收"))
        self.hexDisplay.setText(_translate("mainwindow", "16进制显示"))
        self.comTest.setText(_translate("mainwindow", "串口检测"))
        self.comboBox_baud.setItemText(0, _translate("mainwindow", "9600"))
        self.comboBox_baud.setItemText(1, _translate("mainwindow", "2400"))
        self.comboBox_baud.setItemText(2, _translate("mainwindow", "4800"))
        self.comboBox_baud.setItemText(3, _translate("mainwindow", "12800"))
        self.comboBox_baud.setItemText(4, _translate("mainwindow", "14400"))
        self.comboBox_baud.setItemText(5, _translate("mainwindow", "19200"))
        self.comboBox_baud.setItemText(6, _translate("mainwindow", "38400"))
        self.comboBox_baud.setItemText(7, _translate("mainwindow", "57600"))
        self.comboBox_baud.setItemText(8, _translate("mainwindow", "76800"))
        self.comboBox_baud.setItemText(9, _translate("mainwindow", "115200"))
        self.comboBox_baud.setItemText(10, _translate("mainwindow", "230400"))
        self.comboBox_baud.setItemText(11, _translate("mainwindow", "460800"))
        self.comboBox_stop.setItemText(0, _translate("mainwindow", "1"))
        self.comboBox_data.setItemText(0, _translate("mainwindow", "8"))
        self.comboBox_data.setItemText(1, _translate("mainwindow", "7"))
        self.comboBox_data.setItemText(2, _translate("mainwindow", "6"))
        self.comboBox_data.setItemText(3, _translate("mainwindow", "5"))
        self.comboBox_odd.setItemText(0, _translate("mainwindow", "N"))
        self.comboBox_odd.setItemText(1, _translate("mainwindow", "奇校验"))
        self.comboBox_odd.setItemText(2, _translate("mainwindow", "偶校验"))
        self.openbotton.setText(_translate("mainwindow", "打开串口"))
        self.label_baud.setText(_translate("mainwindow", "波特率"))
        self.label_stop.setText(_translate("mainwindow", "停止位"))
        self.label_data.setText(_translate("mainwindow", "数据位"))
        self.label_odd.setText(_translate("mainwindow", "奇偶校验"))
        self.closebotton.setText(_translate("mainwindow", "关闭串口"))
        self.sendbotton.setText(_translate("mainwindow", "发送"))
        self.hexSend.setText(_translate("mainwindow", "16进制发送"))
        self.xinhang.setText(_translate("mainwindow", "发送新行"))
